version: '3.8'
services:
  eliza:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"      # Main application port
      - "8088:8080"      # Map container's 8080 to host's 8088
    volumes:
      - ./data:/app/data # Persist data
    environment:
      - NODE_ENV=production
      # Add any other environment variables needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30