# Load custom actions from the actions directory

# Clone this into a elizaConfig.yaml file that is ignored by git

# Paths are relative to the core/src directory

actions:
    - name: imageGeneration
      path: ./actions/imageGeneration.ts
      enabled: true
      settings:
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
        TOGETHER_API_KEY: ${TOGETHER_API_KEY}
        TWITTER_API_KEY: ${TWITTER_API_KEY}
        TWITTER_API_SECRET: ${TWITTER_API_SECRET}
        TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
        TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
